services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: builder
      dockerfile: backend.Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:  # these are the test environment variables.
      - FLASK_SERVER_PORT=9091
      - MONGO_DB_NAME=registry
      - MONGO_URI=mongodb://mongo:27017/fpmregistry
      - SALT=MYSALT
      - MONGO_DB_NAME=fpmregistry
      - SUDO_PASSWORD=fortran
      - MONGO_USER_NAME=fortran
      - MONGO_PASSWORD=fortran
      - HOST=localhost
      - RESET_EMAIL=reset@localhost.com
      - RESET_PASSWORD=reset
      - SUDO_PASSWORD=fortran

    volumes:
      - ./flask:/src
    depends_on:
      - mongo

  mongo:
    image: mongo
