services:
  test_ci:
    build:
      context: backend
      target: builder
      dockerfile: docker/backend.Dockerfile
    command: python -m unittest discover -s tests
    volumes:
      - ./tests:/src/tests
      - ./backend:/src
    depends_on:
      - mongo
    environment: # these are the test environment variables.
      - MONGO_DB_NAME=testregistry
      - MONGO_URI=mongodb://mongo:27017/testregistry
      - MONGO_USER_NAME=testuser
      - MONGO_PASSWORD=testpassword
      - SALT=MYSALT
      - HOST=localhost
      - RESET_EMAIL=reset@localhost.com
      - RESET_PASSWORD=reset
      - SUDO_PASSWORD=fortran

  mongo:
    image: mongo

