services:
  test:
    build:
      context: flask
      target: builder
      dockerfile: backend.Dockerfile
    command: python -m unittest discover -s tests
    volumes:
      - ./tests:/src/tests
      - ./flask:/src
    depends_on:
      - tests_db
    environment:
      - MONGO_DB_NAME=testregistry
      - MONGO_URI=mongodb://mongo:27017/testregistry
  tests_db:
    image: mongo
  
  backend:
    build:
      context: flask
      target: builder
      dockerfile: backend.Dockerfile
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
      - MONGO_DB_NAME=registry
      - MONGO_URI=mongodb://mongo:27017/fpmregistry

    volumes:
      - ./flask:/src
    depends_on:
      - mongo

  mongo:
    image: mongo
