services:
  test_ci:
    build:
      context: backend
      target: builder
      dockerfile: docker/backend.Dockerfile
    command: python -m unittest discover -s tests
    volumes:
      - ./backend:/src
    depends_on:
      - mongo
    environment:
      # these are the test environment variables.
      - MONGO_DB_NAME=testregistry
      - MONGO_URI=mongodb://mongo:27017/testregistry
      - MONGO_USER_NAME=testuser
      - MONGO_PASSWORD=testpassword
      - SALT=MYSALT
      - HOST=localhost
      - RESET_EMAIL=reset@localhost.com
      - RESET_PASSWORD=reset
      - SUDO_PASSWORD=SUDO_PASSWORD
      - IS_CI=true

  validate_package:
    build:
      dockerfile: backend/docker/validate_package.Dockerfile
    stop_signal: SIGINT

  mongo:
    image: mongo

