name: Run Tests for Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout page source
        uses: actions/checkout@v3

      - name: Build the Docker image and run tests
        run: docker compose -f "backend/compose.test.yaml" up -d

      - name: Print Logs for Container
        run: |
          export CONTAINER_ID=$(docker ps -aqf "name=test_ci-1")
          docker exec $CONTAINER_ID python -m unittest discover backend/tests

          TEST_EXIT_STATUS=$?

          if [ $TEST_EXIT_STATUS -ne 0 ]; then
            echo "Tests failed. Exiting with status code $TEST_EXIT_STATUS."
            exit 1
          else
            echo "Tests passed."
            exit 0
          fi
