name: Run Tests for Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout page source
      uses: actions/checkout@v3

    - name: Build the Docker image and run tests
      run: docker compose -f "compose.test.yaml" up -d

    - name: set CONTAINER_ID for test Container
      run: CONTAINER_ID=$(docker ps -aqf "name=ci")

    - name: Print Logs for Container
      run: echo $CONTAINER_ID

    - name: Check the actions for test cases
      run: if docker logs -f $CONTAINER_ID 2>&1 | grep -qi 'assertion'; then exit 1; else exit 0; fi



      
      
